config/routes.rb
Cnucamp::Application.routes.draw do
  require 'api'

  resources :sites

  resources :posts
  resources :pages, :path => "wiki" do
    collection do
      get :recent
    end
  end
  resources :comments
  resources :notes
  match "/uploads/*path" => "gridfs#serve"
  match "/introduction" => "home#index", :as => :introduction
  match "/album" => "cnucamp#album",:as => :album
  root :to => "cnucamp#index"
  

  devise_for :users, :path => "account", :controllers => {
      :registrations => :account,
      :omniauth_callbacks => "users/omniauth_callbacks"
    } do
    get "account/update_private_token" => "account#update_private_token", :as => :update_private_token_account
  end

  match "account/auth/:provider/unbind", :to => "users#auth_unbind"

  match "users/location/:id", :to => "users#location", :as => :location_users
  resources :users do
    member do
      get :topics
      get :favorites
    end
  end
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end

  resources :nodes

  match "topics/node:id" => "topics#node", :as => :node_topics
  match "topics/node:id/feed" => "topics#node_feed", :as => :feed_node_topics
  match "topics/last" => "topics#recent", :as => :recent_topics
  resources :topics do
    member do
      post :reply
      post :favorite
    end
    collection do
      get :search
      get :feed
      post :preview
    end
    resources :replies
  end

  resources :photos do
    collection do
      get :tiny_new
    end
  end
  resources :likes

  match "/search" => "search#index", :as => :search
  match "/search/topics" => "search#topics", :as => :search_topics
  match "/search/wiki" => "search#wiki", :as => :search_wiki

  namespace :cpanel do
    root :to => "home#index"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :posts
    resources :pages do
      resources :versions, :controller => :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
  end

  mount Cnucamp::API => "/"

  if Rails.env.development?
    mount UserMailer::Preview => 'mails/user'
  end
end

app/controllers/search_controller.rb
# coding: utf-8
class SearchController < ApplicationController
  def index
    search_text = params[:q]
    @search = Sunspot.search(Topic) do
      keywords search_text, :highlight => true
      paginate :page => params[:page], :per_page => 20
      order_by :replied_at, :desc
    end

    set_seo_meta("#{t("common.search")}: #{params[:q]}")
    drop_breadcrumb("#{t("common.search")}: #{params[:q]}")
  end

  def wiki
    search_text = params[:q]
    @search = Sunspot.search(Page) do
      keywords search_text, :highlight => true
      paginate :page => params[:page], :per_page => 20
    end

    set_seo_meta("WIKI#{t("common.search")}: #{params[:q]}")
    drop_breadcrumb("WIKI#{t("common.search")}: #{params[:q]}")
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def search_result_highlight(hit, key)
    raw hit.highlights(key).collect { |t| t.format { |t1| content_tag(:span, t1, :class => "highlight") } }.join("")
  end
end

app/views/search/_base.html.erb
<% content_for :styles do %>
  <%= stylesheet_link_tag "search" %>
<% end %>

app/views/search/_menu.html.erb
<%= render_list :class => "tabs" do |li|
  li << link_to(t("menu.topics"), search_path(:q => params[:q]))
  li << link_to(t("menu.wiki"), search_wiki_path(:q => params[:q]))
end %>

app/views/search/_page.html.erb
<div class="page">
  <div class="title"><%= link_to(highlight(page.title, @keywords), page_path(page.slug)) %></div>
  <div class="url"><%= link_to(page_url(page.slug), page_path(page.slug)) %></div>
  <div class="info"><%= t("common.published_at")%> <%= timeago(page.updated_at) %></div>
  <div class="summary">
    <%= highlight(truncate(page.body, :length => 300),@keywords) %>
  </div>
</div>

app/views/search/_topic.html.erb
<div class="topic">
  <div class="title"><%= link_to(highlight(topic.title, @keywords), topic_path(topic)) %></div>
  <div class="url"><%= link_to(topic_url(topic), topic_path(topic)) %></div>
  <div class="info"><%= t("common.by") %> <%= user_name_tag(topic.user) %> <%= t("common.published_at")%> <%= timeago(topic.created_at) %> <%= t("common.reply_count")%>: <%= topic.replies_count %></div>
  <div class="summary">
    <%= highlight(truncate(topic.body, :length => 300),@keywords) %>
  </div>
</div>

app/views/search/index.html.erb
<%= render "base" %>

<div class="box">
  <%= render "menu" %>
  <div class="tab-content">
    <div class="tab-pane active" id="topics">
    <% unless @search.results.blank? %>
      <% @search.each_hit_with_result do |hit, result| %>
        <%= render "topic", :topic => result, :hit => hit %>
      <% end %>
    <% else %>
      <div class="topic">
        <%= t("common.no_search_result") %>
      </div>
    <% end %>
    </div>
    <%= will_paginate @search.results %>
  </div>
</div>

app/views/search/wiki.html.erb
<%= render "base" %>

<div class="box">
  <%= render "menu" %>
  <div class="tab-content">
    <div class="tab-pane active" id="pages">
    <% unless @search.results.blank? %>
      <% @search.each_hit_with_result do |hit, result| %>
        <%= render "page", :page => result, :hit => hit %>
      <% end %>
    <% else %>
      <div class="page">
        <%= t("common.no_search_result") %>
      </div>
    <% end %>
    </div>
    <%= will_paginate @search.results %>
  </div>
</div>