config/routes.rb
Cnucamp::Application.routes.draw do
  require 'api'

  resources :sites

  resources :posts
  resources :pages, :path => "wiki" do
    collection do
      get :recent
    end
  end
  resources :comments
  resources :notes
  match "/uploads/*path" => "gridfs#serve"
  match "/introduction" => "home#index", :as => :introduction
  match "/album" => "cnucamp#album",:as => :album
  root :to => "cnucamp#index"
  

  devise_for :users, :path => "account", :controllers => {
      :registrations => :account,
      :omniauth_callbacks => "users/omniauth_callbacks"
    } do
    get "account/update_private_token" => "account#update_private_token", :as => :update_private_token_account
  end

  match "account/auth/:provider/unbind", :to => "users#auth_unbind"

  match "users/location/:id", :to => "users#location", :as => :location_users
  resources :users do
    member do
      get :topics
      get :favorites
    end
  end
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end

  resources :nodes

  match "topics/node:id" => "topics#node", :as => :node_topics
  match "topics/node:id/feed" => "topics#node_feed", :as => :feed_node_topics
  match "topics/last" => "topics#recent", :as => :recent_topics
  resources :topics do
    member do
      post :reply
      post :favorite
    end
    collection do
      get :search
      get :feed
      post :preview
    end
    resources :replies
  end

  resources :photos do
    collection do
      get :tiny_new
    end
  end
  resources :likes

  match "/search" => "search#index", :as => :search
  match "/search/topics" => "search#topics", :as => :search_topics
  match "/search/wiki" => "search#wiki", :as => :search_wiki

  namespace :cpanel do
    root :to => "home#index"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :posts
    resources :pages do
      resources :versions, :controller => :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
  end

  mount Cnucamp::API => "/"

  if Rails.env.development?
    mount UserMailer::Preview => 'mails/user'
  end
end

app/models/topic.rb
# coding: utf-8
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::BaseModel
  include Mongoid::SoftDelete
  include Mongoid::CounterCache
  include Mongoid::Likeable
  include Mongoid::MarkdownBody
  include Redis::Objects
  include Sunspot::Mongoid

  field :title
  field :body
  field :body_html
  field :last_reply_id, :type => Integer
  field :replied_at , :type => DateTime
  field :source
  field :message_id
  field :replies_count, :type => Integer, :default => 0
  # 回复过的人的 ids 列表
  field :follower_ids, :type => Array, :default => []
  field :suggested_at, :type => DateTime
  field :likes_count, :type => Integer, :default => 0
  # 最后回复人的用户名 - cache 字段用于减少列表也的查询
  field :last_reply_user_login
  # 节点名称 - cache 字段用于减少列表也的查询
  field :node_name
  # 删除人
  field :who_deleted

  belongs_to :user, :inverse_of => :topics
  counter_cache :name => :user, :inverse_of => :topics
  belongs_to :node
  counter_cache :name => :node, :inverse_of => :topics
  belongs_to :last_reply_user, :class_name => 'User'
  has_many :replies, :dependent => :destroy

  attr_accessible :title, :body
  validates_presence_of :user_id, :title, :body, :node_id

  index :node_id
  index :user_id
  index :replied_at
  index :created_at
  index :links_count
  index :suggested_at

  counter :hits, :default => 0

  searchable do
    text :title, :stored => true, :more_like_this => true
    text :body, :stored => true, :more_like_this => true
    text :replies, :stored => true, :more_like_this => true do
      replies.map { |reply| reply.body }
    end
    integer :node_id, :user_id
    boolean :deleted_at
    time :replied_at
  end

  # scopes
  scope :last_actived, desc("replied_at").desc("created_at")
  # 推荐的话题
  scope :suggest, where(:suggested_at.ne => nil).desc(:suggested_at)
  scope :fields_for_list, without(:body,:body_html)
  scope :high_likes, desc(:likes_count, :_id)
  scope :high_replies, desc(:replies_count, :_id)

  before_save :store_cache_fields
  def store_cache_fields
    self.node_name = self.node.try(:name) || ""
  end

  before_create :init_replied_at_on_create
  def init_replied_at_on_create
    self.replied_at = Time.now if self.replied_at.blank?
  end

  def push_follower(user_id)
    self.follower_ids << user_id if !self.follower_ids.include?(user_id)
  end

  def pull_follower(user_id)
    self.follower_ids.delete(user_id)
  end

  def update_last_reply(reply)
    self.replied_at = Time.now
    self.last_reply_id = reply.id
    self.last_reply_user_id = reply.user_id
    self.last_reply_user_login = reply.user.try(:login) || nil
    self.push_follower(reply.user_id)
    self.save
  end

  def self.find_by_message_id(message_id)
    where(:message_id => message_id).first
  end
  
  # 删除并记录删除人
  def destroy_by(user)
    return false if user.blank?
    self.update_attribute(:who_deleted,user.login)
    self.destroy
  end
end

app/controllers/cpanel/topics_controller.rb
# coding: utf-8
class Cpanel::TopicsController < Cpanel::ApplicationController

  def index
    @topics = Topic.unscoped.desc(:_id).includes(:user).paginate :page => params[:page], :per_page => 30

  end

  def show
    @topic = Topic.unscoped.find(params[:id])

  end


  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.unscoped.find(params[:id])
  end

  def create
    @topic = Topic.new(params[:topic])

    if @topic.save
      redirect_to(cpanel_topics_path, :notice => 'Topic was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @topic = Topic.unscoped.find(params[:id])

    if @topic.update_attributes(params[:topic])
      redirect_to(cpanel_topics_path, :notice => 'Topic was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @topic = Topic.unscoped.find(params[:id])
    @topic.destroy_by(current_user)

    redirect_to(cpanel_topics_path)
  end

  def undestroy
    @topic = Topic.unscoped.find(params[:id])
    @topic.update_attribute(:deleted_at, nil)
    redirect_to(cpanel_topics_path)
  end

  def suggest
    @topic = Topic.unscoped.find(params[:id])
    @topic.update_attribute(:suggested_at, Time.now)
    CacheVersion.topic_last_suggested_at = Time.now
    redirect_to(cpanel_topics_path, :notice => "Topic:#{params[:id]} suggested.")
  end

  def unsuggest
    @topic = Topic.unscoped.find(params[:id])
    @topic.update_attribute(:suggested_at, nil)
    CacheVersion.topic_last_suggested_at = Time.now
    redirect_to(cpanel_topics_path, :notice => "Topic:#{params[:id]} unsuggested.")
  end
end

app/controllers/topics_controller.rb
# coding: utf-8
class TopicsController < ApplicationController

  load_and_authorize_resource :only => [:new,:edit,:create,:update,:destroy,:favorite]

  before_filter :set_menu_active
  caches_page :feed, :node_feed, :expires_in => 1.hours
  before_filter :init_base_breadcrumb

  def index
    @topics = Topic.last_actived.fields_for_list.limit(15).includes(:user)
    set_seo_meta("","#{Setting.app_name}#{t("menu.topics")}")
    drop_breadcrumb(t("topics.hot_topic"))
    #render :stream => true
  end

  def feed
    @topics = Topic.recent.without_body.limit(20).includes(:node,:user, :last_reply_user)
    response.headers['Content-Type'] = 'application/rss+xml; charset=utf-8'
    render :layout => false
  end

  def node
    @node = Node.find(params[:id])
    @topics = @node.topics.last_actived.fields_for_list.includes(:user).paginate(:page => params[:page],:per_page => 50)
    set_seo_meta("#{@node.name} &raquo; #{t("menu.topics")}","#{Setting.app_name}#{t("menu.topics")}#{@node.name}",@node.summary)
    drop_breadcrumb("#{@node.name}")
    render :action => "index" #, :stream => true
  end

  def node_feed
    @node = Node.find(params[:id])
    @topics = @node.topics.recent.without_body.limit(20)
    response.headers["Content-Type"] = "application/rss+xml"
    render :layout => false
  end

  def recent
    # TODO: 需要 includes :node,:user, :last_reply_user,但目前用了 paginate 似乎会使得 includes 没有效果
    @topics = Topic.recent.fields_for_list.includes(:user).paginate(:page => params[:page], :per_page => 50)
    drop_breadcrumb(t("topics.topic_list"))
    render :action => "index" #, :stream => true
  end

  def search
    result = Redis::Search.query("Topic", params[:key], :limit => 500)
    ids = result.collect { |r| r["id"] }
    @topics = Topic.where(:_id.in => ids).limit(50).includes(:node,:user, :last_reply_user)
    set_seo_meta("#{t("common.search")}#{params[:s]} &raquo; #{t("menu.topics")}")
    drop_breadcrumb("#{t("common.search")} #{params[:key]}")
    render :action => "index" #, :stream => true
  end

  def show
    @topic = Topic.without_body.includes(:user, :node).find(params[:id])
    @topic.hits.incr(1)
    @node = @topic.node
    @replies = @topic.replies.without_body.asc(:_id).all.includes(:user).reject { |r| r.user.blank? }
    if current_user
      current_user.read_topic(@topic)
      # TODO: 此处导致每次查看帖子都会执行 update 需要改进
      current_user.notifications.where(:reply_id.in => @replies.map(&:id), :read => false).update_all(:read => true)
    end
    set_seo_meta("#{@topic.title} &raquo; #{t("menu.topics")}")
    drop_breadcrumb("#{@node.name}", node_topics_path(@node.id))
    drop_breadcrumb t("topics.read_topic")
   # render :stream => true
  end

  def new
    @topic = Topic.new
    if !params[:node].blank?
      @topic.node_id = params[:node]
      @node = Node.find_by_id(params[:node])
      if @node.blank?
        render_404
      end
      drop_breadcrumb("#{@node.name}", node_topics_path(@node.id))
    end
    drop_breadcrumb t("topics.post_topic")
    set_seo_meta("#{t("topics.post_topic")} &raquo; #{t("menu.topics")}")
  end

  def edit
    @topic = Topic.find(params[:id])
    @node = @topic.node
    drop_breadcrumb("#{@node.name}", node_topics_path(@node.id))
    drop_breadcrumb t("topics.edit_topic")
    set_seo_meta("#{t("topics.edit_topic")} &raquo; #{t("menu.topics")}")
  end

  def create
    pt = params[:topic]
    @topic = Topic.new(pt)
    @topic.user_id = current_user.id
    @topic.node_id = params[:node] || pt[:node_id]

    if @topic.save
      redirect_to(topic_path(@topic.id), :notice => t("topics.create_topic_success"))
    else
      render :action => "new"
    end
  end

  def preview
    @body = params[:body]

    respond_to do |format|
      format.json
    end
  end

  def update
    @topic = Topic.find(params[:id])
    pt = params[:topic]
    @topic.node_id = pt[:node_id]
    @topic.title = pt[:title]
    @topic.body = pt[:body]

    if @topic.save
      redirect_to(topic_path(@topic.id), :notice =>  t("topics.update_topic_success"))
    else
      render :action => "edit"
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy_by(current_user)
    redirect_to(topics_path, :notice => t("topics.delete_topic_success"))
  end
  
  def favorite
    if params[:type] == "unfavorite"
      current_user.unfavorite_topic(params[:id])
    else
      current_user.favorite_topic(params[:id])
    end
    render :text => "1"
  end

  protected

  def set_menu_active
    @current = @current = ['/topics']
  end

  def init_base_breadcrumb
    drop_breadcrumb(t("menu.topics"), topics_path)
  end

  private

  def init_list_sidebar
   if !fragment_exist? "topic/init_list_sidebar/hot_nodes"
      @hot_nodes = Node.hots.limit(10)
    end
    set_seo_meta(t("menu.topics"))
  end

end

app/helpers/topics_helper.rb
# coding: utf-8
require 'digest/md5'
module TopicsHelper
  def format_topic_body(text)
    MarkdownTopicConverter.format(text)
  end

  def topic_use_readed_text(state)
    case state
    when true
      t("topics.have_no_new_reply")
    else
      t("topics.has_new_replies")
    end
  end
  
  def topic_favorite_tag(topic)
    return "" if current_user.blank?
    class_name = "bookmark"
    link_title = "收藏"
    if current_user and current_user.favorite_topic_ids.include?(topic.id)
      class_name = "bookmarked"
      link_title = "取消收藏"
    end
    
    link_to "", "#", :onclick => "return Topics.favorite(this);", 'data-id' => topic.id, :class => "icon small_#{class_name}", :title => link_title, :rel => "twipsy"
  end

  def render_topic_title(topic)
    return t("topics.topic_was_deleted") if topic.blank?
    link_to(topic.title, topic_path(topic), :title => topic.title)
  end

  def render_topic_last_reply_time(topic)
    l((topic.replied_at || topic.created_at), :format => :short)
  end

  def render_topic_count(topic)
    topic.replies_count
  end

  def render_topic_created_at(topic)
    timeago(topic.created_at)
  end

  def render_topic_last_be_replied_time(topic)
    timeago(topic.replied_at)
  end

  def render_topic_node_select_tag(topic)
    return if topic.blank?
    grouped_collection_select :topic, :node_id, Section.all, 
                    :sorted_nodes, :name, :id, :name, :value => topic.node_id,
                    :include_blank => true, :prompt => "选择节点"
  end
end

app/views/topics/_editor_toolbar.html.erb
<div class="editor_toolbar">
  <div class="icons pull-right">
    <%= link_to("", "#", :onclick => "return Topics.addImageClick();", :id => "add_image", :rel => "twipsy", :title => t("topics.add_image"), :class => "icon small_image")%>
  </div>
  <ul class="pills" style="clear:none;">
    <li class="edit active"><%= link_to(t("common.editor_toolbar_edit"), "#") %></li>
    <li class="preview"><%= link_to(t("common.editor_toolbar_preview"), "#") %></li>
  </ul>
</div>

app/views/topics/_form.html.erb
<%= simple_form_for @topic, :wrapper => :inline do |f| %>
  <fieldset>
    <legend><%= @topic.new_record? ? t("topics.create_topic") : t("topics.edit_topic") %></legend>
    <%= render "shared/error_messages", :target => @topic %>  
    <%= f.input :title do %>
      <span class="span3">
        <%= render_topic_node_select_tag(@topic) %>
      </span>
      <span class="span6">
        <%= f.text_field :title %>
      </span>
    <% end %>
    
    <div class="edit_tools input">
      <%= render "editor_toolbar" %>
    </div>    
    <%= f.input :body, :as => :text, :input_html => { :class => "topic_editor closewarning xxlarge", :style => "height:400px" }%>

    <div class="actions">
      <%= f.submit t("common.save"), :class => "btn primary", :disable_with => t("common.saving") %>
      <%= link_to(t("common.cancel"), @topic.id.blank? ? root_path : topic_path(@topic), :class => "btn")%>
    </div>
  </fieldset>
<% end %>

app/views/topics/_node_info.html.erb
<% if !node.blank? %>
  <div>
    <h2><%= node.name %></h2>
    <span class="total">共有 <%= render_node_topics_count(node) %> 个讨论主题</span>
    <div class="feed">
      <%= link_to("#{content_tag(:span, "", :class => "icon share_icons_rss" )}".html_safe, feed_node_topics_url, :title => "#{node.name} Feed") %>
    </div>
  </div>
  <div class="desc">
    <%= simple_format(node.summary) %>
  </div>
<% else %>
  <h1><%= Setting.app_name %></h1>
<% end %>

app/views/topics/_replies.html.erb
<% if replies.blank? %>
  <div class="no_result">
    <%= t("topics.no_replies") %>
  </div>
<% else %>
<div id="replies" class="box">
  <%= render "topics/translation/topic_reply_statics", :topic => topic %>
  <%= render :partial => "replies/reply", :collection => replies %>
</div>
<% end %>

app/views/topics/_sidebar_for_gadget.html.erb
<div id="ruby-group-promote" class="box">
  <div id="feedGadget">Loading...</div>
</div>

<% content_for(:scripts) do  %>
<!-- welcome page sidebar js -->
<script src="http://www.google.com/jsapi/?key=<%= Setting.google_js_api_key %>"
  type="text/javascript"></script>
<%= javascript_include_tag("gfdynamicfeedcontrol") %>
<script type="text/javascript">
  function showGadget() {
    var feeds = [
     {title:'<%= t("common.hot_topics") %>',
      url:'<%= Setting.external_feed_url%>'}];

    new GFdynamicFeedControl(feeds, 'feedGadget',
                             {numResults : 10, stacked : true,
                              title: "<%= Setting.external_feed_name %>"});
  }
  google.load("feeds", "1");
  google.setOnLoadCallback(showGadget);
</script>
<% end %>

app/views/topics/_sidebar_for_new_topic.html.erb
<div class="sidebar">
    <%= render_cell :topics, :sidebar_for_new_topic_node, { :node => @node } %>
    <div id="topic_new_tip" class="box">
      <h2><%= t("topics.tips_for_create_topic")%></h2>
      <span class="body help-block">
         <%= render_cell :topics, :reply_help_block %>
      </span>
    </div>
</div>

app/views/topics/_sidebar_for_topic_index.html.erb
<%= render :partial => "sidebar_new_topic_box"%>
<%= render_cell :topics, :sidebar_suggest_topics %>
<%# render :partial => "sidebar_for_gadget" %>
<%= raw SiteConfig.topic_index_sidebar_html %>
<%= render_cell :topics, :sidebar_hot_nodes %>
<%= render_cell :topics, :sidebar_statistics %>

app/views/topics/_sidebar_for_topic_node.html.erb
<%= render_cell :topics, :sidebar_for_new_topic_node, { :node => @node } %>
<%= raw SiteConfig.topic_index_sidebar_html %>
<%= render_cell :topics, :sidebar_hot_nodes %>

app/views/topics/_sidebar_for_topic_recent.html.erb
<%= render :partial => "sidebar_new_topic_box" %>
<%= raw SiteConfig.topic_index_sidebar_html %>
<%= render_cell :topics, :sidebar_hot_nodes %>

app/views/topics/_topic.html.erb
<div class="topic topic_line">
  <div class="pull-left avatar">
    <%= user_avatar_tag(topic.user,:normal) %>
  </div>
  <div class="right_info">
    <div class="pull-right replies">
      <% if topic.replies_count > 0 %>
        <% read_state = current_user.try(:topic_read?,topic) %>
        <%= link_to(topic.replies_count,topic_path(topic)+"#reply#{topic.replies_count}",
          :rel => "twipsy",
          :title => "#{topic_use_readed_text(read_state) if current_user}",
          :class => "count state_#{read_state || false}"
        )%>
      <% end %>
    </div>
    <div class="infos">
      <div class="title">
          <%= link_to(truncate(topic.title, :length => 100), topic_path(topic), :title => topic.title) %>
      </div>
      <div class="info leader">
        <%= t("common.by") %> <%= user_name_tag(topic.user) %>
        <%= t("common.at") %> <%= render_node_name(topic.node_name,topic.node_id) %> <%= t("common.create_item")%>
      </div>
      <div class="info time">
        <% if topic.last_reply_user_login.blank? %>
          <%= raw t("common.created_at", :time => timeago(topic.created_at))%>
        <% else %>
          <%= t("common.last_by")%> <%= user_name_tag(topic.last_reply_user_login) %> <%= raw t("common.reply_at", :time => timeago(topic.replied_at))%>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/_topic_info.html.erb
<div class="infos">
  <h1><%= truncate(topic.title, :length => 100) %></h1>
  <div class="info leader">
    <%= render_topic_created_at(topic) %> <%= t("common.by") %> 
    <span class="name"><%= user_name_tag(topic.user) %></span>
    <%= t("common.at") %> <%= render_node_name(topic.node_name, topic.node_id) %> <%= t("menu.nodes")%> <%= t("common.create_item")%>
  </div>
  <div class="info time">
    <% if not topic.last_reply_user_id.blank? %>
      <%= t("common.last_by")%> <%= user_name_tag(topic.last_reply_user) %> <%= raw t("common.reply_at", :time => render_topic_last_be_replied_time(topic)) %> ,
    <% end %>
    <%= topic.hits %><%= t("common.read_times")%>
  </div>
</div>

app/views/topics/index.html.erb
<%= render "base" %>

<div class="content">
  <div class="box">
    <div id="node_info">
      <%= render "node_info", :node => @node %>
    </div>

    <div class="topics">
      <%= render :partial => "topics/topic", :collection => @topics %>
    </div>
     
      
    <% if ["index","search"].include?(action_name) %>
      <div class="more">
        <%= link_to(t("topics.check_recent_topics"), recent_topics_path)%>
      </div>
    <% else %>
      <%= will_paginate @topics %>
    <% end %>
    </div>
    
    <% if action_name == "index" %>
      <%= render_cell :topics, :index_sections %>
      <%# render_cell :topics, :index_locations %>
    <% end %>

    <% if !@node.blank? %>
      <% content_for :node_feed_link do %>
        <%= auto_discovery_link_tag(:rss, feed_node_topics_url, :title => "#{@node.name}節點最新話題") %>
      <% end %>
    <% end %>

</div>

<div class="sidebar">
    <%= render "sidebar_for_topic_index" if action_name == "index" %>
    <%= render "sidebar_for_topic_recent" if action_name == "recent" %>
    <%= render "sidebar_for_topic_node" if action_name == "node" %>
</div>

app/views/topics/preview.json.erb
<%= {:body => format_topic_body(@body)}.to_json.html_safe %>

app/views/topics/show.html.erb
<%= render 'base' %>

<div class="content">
  <div id="topic_show" class="topics box clearfix">
    <div class="topic">
      <div class="pull-right avatar_large">
        <%= user_avatar_tag(@topic.user, :large, :link => false) %>
      </div>

      <%= render :partial => "topics/topic_info", :locals => { :topic => @topic} %>

      <%= raw SiteConfig.before_topic_html %>

      <div class="body">
        <%= raw @topic.body_html %>
      </div>

      <%= raw SiteConfig.after_topic_html %>

      <div class="tools pull-right">
        <%= likeable_tag(@topic) %>
        <%= topic_favorite_tag(@topic) %>
        <% if owner?(@topic) or admin? %>
          <%= link_to "", edit_topic_path(@topic), :class => "icon small_edit", :title => "修改本帖" %>
          <%= link_to "", topic_path(@topic.id), :method => :delete, :confirm => t("common.confirm_delete"), :class => "icon small_delete", :title => "删除本帖" %>
        <% end %>
      </div>
      <%# social_share_button_tag("#{@topic.title} via: @#{Setting.twitter_id} ") %>
    </div>
  </div>

  <%= render :partial => "topics/replies", :locals => { :topic => @topic, :replies => @replies } %>

  <% if current_user %>
    <div id="reply" class="form box">
      <%= render "editor_toolbar" %>
      <%= form_for(Reply.new, :remote => true,:url => topic_replies_path(@topic)) do |f| %>
        <%= f.text_area :body,:class => "topic_editor span10", :rows => "4", :tabindex => "1" %>
        <div class="submit_buttons">
          <button type="submit" id="btn_reply" class="btn primary" tabindex="2"><%= t("topics.submit_reply")%></button><br />
          <span class="help-inline">Ctrl+Enter</span>
        </div>
        
        <span class="body helpblock">
          <%= render_cell :topics, :reply_help_block %>
        </span>
      <% end %>
    </div>
  <% else %>
      <%= render :partial => "topics/translation/need_login_to_reply" %>
  <% end %>
</div>

<div class="sidebar">
    <%= render_cell :topics, :sidebar_for_new_topic_node, { :action => params[:action], :node => @node } %>
    <%= render_cell :topics, :sidebar_for_more_like_this, { :topic => @topic} %>
</div>