config/routes.rb
Cnucamp::Application.routes.draw do
  require 'api'

  resources :sites

  resources :posts
  resources :pages, :path => "wiki" do
    collection do
      get :recent
    end
  end
  resources :comments
  resources :notes
  match "/uploads/*path" => "gridfs#serve"
  match "/introduction" => "home#index", :as => :introduction
  match "/album" => "cnucamp#album",:as => :album
  root :to => "cnucamp#index"
  

  devise_for :users, :path => "account", :controllers => {
      :registrations => :account,
      :omniauth_callbacks => "users/omniauth_callbacks"
    } do
    get "account/update_private_token" => "account#update_private_token", :as => :update_private_token_account
  end

  match "account/auth/:provider/unbind", :to => "users#auth_unbind"

  match "users/location/:id", :to => "users#location", :as => :location_users
  resources :users do
    member do
      get :topics
      get :favorites
    end
  end
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end

  resources :nodes

  match "topics/node:id" => "topics#node", :as => :node_topics
  match "topics/node:id/feed" => "topics#node_feed", :as => :feed_node_topics
  match "topics/last" => "topics#recent", :as => :recent_topics
  resources :topics do
    member do
      post :reply
      post :favorite
    end
    collection do
      get :search
      get :feed
      post :preview
    end
    resources :replies
  end

  resources :photos do
    collection do
      get :tiny_new
    end
  end
  resources :likes

  match "/search" => "search#index", :as => :search
  match "/search/topics" => "search#topics", :as => :search_topics
  match "/search/wiki" => "search#wiki", :as => :search_wiki

  namespace :cpanel do
    root :to => "home#index"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :posts
    resources :pages do
      resources :versions, :controller => :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
  end

  mount Cnucamp::API => "/"

  if Rails.env.development?
    mount UserMailer::Preview => 'mails/user'
  end
end

app/models/notification/base.rb
class Notification::Base
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::BaseModel

  store_in :notifications

  field :read, :default => false

  scope :unread, where(:read => false)

  belongs_to :user

  index [[:user_id, Mongo::ASCENDING], [:read, Mongo::ASCENDING]]

  def anchor
    "notification-#{id}"
  end
end

app/models/notification/mention.rb
class Notification::Mention < Notification::Base
  belongs_to :reply
end

app/models/notification/topic_reply.rb
class Notification::TopicReply < Notification::Base
  belongs_to :reply
end

app/controllers/notifications_controller.rb
# coding: utf-8
class NotificationsController < ApplicationController
  before_filter :require_user
  respond_to :html, :js, :only => [:destroy, :mark_all_as_read]

  def index
    @notifications = current_user.notifications.recent.paginate :page => params[:page], :per_page => 20
    current_user.read_notifications(@notifications)
    set_seo_meta("提醒")
  end

  def destroy
    @notification = current_user.notifications.find params[:id]
    @notification.destroy
    respond_with do |format|
      format.html { redirect_referrer_or_default notifications_path }
      format.js { render :layout => false }
    end
  end

  def mark_all_as_read
    current_user.notifications.unread.update_all(:read => true)
    respond_with do |format|
      format.html { redirect_referrer_or_default notifications_path }
      format.js { render :layout => false }
    end
  end
end

app/views/notifications/destroy.js.erb
$('#' + '<%= @notification.anchor %>').fadeOut('normal', function(){
  $(this).remove();
});

app/views/notifications/index.html.erb
<%= content_for :styles do %>
  <%= stylesheet_link_tag "notifications" %>
<% end %>
<%= content_for :scripts do %>
  <%= javascript_include_tag "notifications" %>
<% end %>

<div id="notifications" class="box">
  <div class="tools">
    <%= link_to t("common.mark_all_as_read"), mark_all_as_read_notifications_path, :class => 'btn', :method => :put, :remote => true, :disable_with => '标记所有为已读...' %>
    <h1 class="pull-right">提醒</h1>
  </div>
  <table>
    <tbody>
      <% @notifications.each do |notification| -%>
        <tr id="<%= notification.anchor %>">
          <%= render :partial => "notifications/#{notification.class.name.underscore}", :locals => {:notification => notification} %>
          <td class="last">
            <%= link_to t("common.delete"), notification_path(notification), :method => :delete, :remote => true, :class => 'label delete' %>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
  <%= will_paginate @notifications %>
</div>

app/views/notifications/mark_all_as_read.js.erb
$('.topbar .notifications').removeClass('unread').find('.count').text('0');
$('#notifications span.new').fadeOut('fast', function(){
  $(this).remove();
});